# Convolution from scratch

In [1]:
import numpy as np
image = np.array([
  [1,2,3,0,1],
  [0,1,2,3,2],
  [3,0,1,2,1],
  [2,1,3,0,0],
  [1,2,0,1,2]
])

image.shape

(5, 5)

In [2]:
import numpy as np

#Define a simple 5X5 grayscale image
image = np.array([
  [1,2,3,0,1],
  [0,1,2,3,2],
  [3,0,1,2,1],
  [2,1,3,0,0],
  [1,2,0,1,2]
])

#Define a 3X3 kernel (filter)
kernel = np.array([
    [0,1,0],
    [1,-4,1],
    [0,1,0]
])

#Deine convolution operation
def convolve(image, kernel):
    # Get height and width of image
    image_h, image_w = image.shape

    # Get height and width of kernel
    kernel_h, kernel_w = kernel.shape

    # Calculate output size (no padding, stride = 1)
    output_h = image_h - kernel_h + 1
    output_w = image_w - kernel_w + 1

    # Create empty output matrix
    output = np.zeros((output_h, output_w))

    # Slide kernel vertically over the image
    for i in range(output_h):

        # Slide kernel horizontally over the image
        for j in range(output_w):

            # Extract the current 3x3 region from the image
            image_patch = image[i:i+kernel_h, j:j+kernel_w]

            # Element-wise multiply image patch and kernel,
            # then sum all values to get a single number
            output[i, j] = np.sum(image_patch * kernel)

    return output


#Apply the convolution
output = convolve(image, kernel)
print(output)

[[  0.   0.  -6.]
 [  6.   3.  -3.]
 [  3. -10.   6.]]


# Padding with Stride=1

In [6]:
#Adding padidng
def pad_image(image, pad):
    return np.pad(image, pad, mode='constant', constant_values=0) #zero padding

pad_image(image, 1)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0, 1, 0],
       [0, 0, 1, 2, 3, 2, 0],
       [0, 3, 0, 1, 2, 1, 0],
       [0, 2, 1, 3, 0, 0, 0],
       [0, 1, 2, 0, 1, 2, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [8]:
import numpy as np

# Function to add zero-padding around the image
def pad_image(image, pad):
    # np.pad adds padding to the image
    # pad specifies how many pixels to add on each side
    # mode='constant' with constant_values=0 means zero padding
    return np.pad(image, pad, mode='constant', constant_values=0)

# Function to perform 2D convolution with stride and padding
def convolve_with_padding_and_stride(image, kernel, stride=1, padding=0):

    # Apply padding to the image if padding > 0
    if padding > 0:
        image = pad_image(image, padding)

    # Get dimensions of the padded image
    image_h, image_w = image.shape

    # Get dimensions of the kernel/filter
    kernel_h, kernel_w = kernel.shape

    # Calculate output feature map dimensions
    # Formula: ((input_size - kernel_size) // stride) + 1
    output_h = (image_h - kernel_h) // stride + 1
    output_w = (image_w - kernel_w) // stride + 1

    # Initialize the output feature map with zeros
    output = np.zeros((output_h, output_w))

    # Slide the kernel over the image with the given stride
    for i in range(0, output_h * stride, stride):
        for j in range(0, output_w * stride, stride):

            # Extract the current region of interest from the image
            region = image[i:i + kernel_h, j:j + kernel_w]

            # Element-wise multiplication followed by summation
            output[i // stride, j // stride] = np.sum(region * kernel)

    # Return the convolved output
    return output


#Define a simple 5X5 grayscale image
image = np.array(
  [
    [1,2,3,0,1],
    [0,1,2,3,2],
    [3,0,1,2,1],
    [2,1,3,0,0],
    [1,2,0,1,2]
])

#Apply the convolution with padding and stride
padded_output = convolve_with_padding_and_stride(image, kernel, stride=1, padding=1)
print("Padding Convolution Output:\n", padded_output)

Padding Convolution Output:
 [[ -2.  -3.  -8.   7.  -2.]
 [  5.   0.   0.  -6.  -3.]
 [-10.   6.   3.  -3.   0.]
 [ -3.   3. -10.   6.   3.]
 [  0.  -6.   6.  -2.  -7.]]


# Max Pooling

In [28]:
import numpy as np

# Max Pooling function
def max_pooling(image, pool_size, stride):

    # Get the height and width of the input image
    image_h, image_w = image.shape

    # Calculate output dimensions after pooling
    # Formula: ((input_size - pool_size) // stride) + 1
    output_h = (image_h - pool_size) // stride + 1
    output_w = (image_w - pool_size) // stride + 1

    # Initialize the output feature map with zeros
    output = np.zeros((output_h, output_w))

    # Slide the pooling window over the image using the given stride
    for i in range(0, output_h * stride, stride):
        for j in range(0, output_w * stride, stride):

            # Extract the current pooling window
            region = image[i:i + pool_size, j:j + pool_size]

            # Take the maximum value from the region
            output[i // stride, j // stride] = np.max(region)

    # Return the pooled output
    return output

# Input image (2D feature map)
image = np.array(
    [
        [1, 2, 3, 0, 1],
        [0, 1, 2, 3, 2],
        [3, 0, 1, 2, 1],
        [2, 1, 3, 0, 0],
        [1, 2, 0, 1, 2]
    ]
)

# Apply max pooling with a 2x2 window and stride of 2
pooled_output = max_pooling(image, pool_size=2, stride=2)

# Print the result
print("Max Pooling Output:\n", pooled_output)


Max Pooling Output:
 [[2. 3.]
 [3. 3.]]


# Convolution on RGB Images

In [12]:
import numpy as np

#Define a simple 5X5X3 RGB image (3 channels)
image = np.array([
    [[1,0,2], [2,1,1], [3,2,0], [0,1,1], [1,0,2]],
    [[0,1,0], [1,0,1], [2,2,2], [3,1,3], [2,0,1]],
    [[3,0,2], [0,1,0], [1,0,1], [2,2,2], [1,0,0]],
    [[2,1,1], [1,0,2], [3,3,1], [0,1,0], [0,2,1]],
    [[1,2,2], [2,1,0], [0,0,1], [1,2,2], [2,1,1]],
])

image.shape

(5, 5, 3)

In [13]:
kernel = np.array([
    [[0,1,0], [1,-1,0], [0,1,0]],
    [[1,0,1], [0,-1,0],[1,0,1]],
    [[0,1,0], [1,1,1], [0,1,0]]
])

kernel.shape

(3, 3, 3)

In [32]:
import numpy as np

#Define a simple 5X5X3 RGB image (3 channels)
image = np.array([
    [[1,0,2], [2,1,1], [3,2,0], [0,1,1], [1,0,2]],
    [[0,1,0], [1,0,1], [2,2,2], [3,1,3], [2,0,1]],
    [[3,0,2], [0,1,0], [1,0,1], [2,2,2], [1,0,0]],
    [[2,1,1], [1,0,2], [3,3,1], [0,1,0], [0,2,1]],
    [[1,2,2], [2,1,0], [0,0,1], [1,2,2], [2,1,1]],
])

image_h, image_w, image_c = image.shape
print(image_h, image_w, image_c)
kernel_h, kernel_w, kernel_c = kernel.shape
print(kernel_h, kernel_w, kernel_c)
output_h = image_h - kernel_h + 1
output_w = image_w - kernel_w + 1
output = np.zeros((output_h, output_w,1))
output.shape

5 5 3
3 3 3


(3, 3, 1)

In [33]:
for k in range(image_c): #Apply the convolution for each channel
  for i in range(output_h):
    for j in range(output_w):
      # print(np.sum(image[i:i + kernel_h, j:j + kernel_w, k] * kernel))
      output[i, j] = np.sum(image[i:i + kernel_h, j:j + kernel_w, k] * kernel)
  #     break
  #   break
  # break

output

array([[[ 8.],
        [ 9.],
        [11.]],

       [[15.],
        [13.],
        [11.]],

       [[ 7.],
        [11.],
        [14.]]])

In [34]:
import numpy as np

# Define a simple 5x5 RGB image (Height x Width x Channels)
# Each pixel has 3 values corresponding to R, G, and B channels
image = np.array([
    [[1,0,2], [2,1,1], [3,2,0], [0,1,1], [1,0,2]],
    [[0,1,0], [1,0,1], [2,2,2], [3,1,3], [2,0,1]],
    [[3,0,2], [0,1,0], [1,0,1], [2,2,2], [1,0,0]],
    [[2,1,1], [1,0,2], [3,3,1], [0,1,0], [0,2,1]],
    [[1,2,2], [2,1,0], [0,0,1], [1,2,2], [2,1,1]],
])

# Define a 3x3x3 convolution filter (kernel)
# One 3x3 kernel per channel (R, G, B)
kernel = np.array([
    [[0,1,0], [1,-1,0], [0,1,0]],
    [[1,0,1], [0,-1,0], [1,0,1]],
    [[0,1,0], [1,1,1], [0,1,0]]
])


#Convolution operation
def convolve_rgb(image, kernel):
  image_h, image_w, image_c = image.shape
  kernel_h, kernel_w, kernel_c = kernel.shape
  output_h = image_h - kernel_h + 1
  output_w = image_w - kernel_w + 1
  output = np.zeros((output_h, output_w,1))
   # Loop over each channel (R, G, B)
  for k in range(image_c): #Apply the convolution for each channel
    for i in range(output_h):  # Slide the kernel vertically
      for j in range(output_w): # Slide the kernel horizontally
        output[i, j] = np.sum(image[i:i + kernel_h, j:j + kernel_w, k] * kernel)

  return output

#Apply the convolution
output = convolve_rgb(image, kernel)
print("Convolution Output:\n",output)

Convolution Output:
 [[[ 8.]
  [ 9.]
  [11.]]

 [[15.]
  [13.]
  [11.]]

 [[ 7.]
  [11.]
  [14.]]]
