# Question 4: Image Filtering and Transformation

In [2]:
#lets create kernel

size = 7

if size % 2 == 0:
  size += 1
print(size)

7


In [4]:
import numpy as np
ax = np.linspace(-(size // 2), size // 2, size)
ax

array([-3., -2., -1.,  0.,  1.,  2.,  3.])

In [6]:
xx, yy = np.meshgrid(ax, ax)
print(xx)

[[-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]]


In [7]:
print(yy)

[[-3. -3. -3. -3. -3. -3. -3.]
 [-2. -2. -2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.  3.  3.]]


In [8]:
sigma = 1

#Compute the Gaussian kernel
kernel = np.exp(-0.5 * (xx**2 + yy**2) / sigma**2)

#Normalize the kernel
kernel /= (2 * np.pi * sigma**2)

In [5]:
 import numpy as np

def gaussian_kernel(size: int, sigma: float) -> np.ndarray:
  """Create a Gaussian model.

  Args:
    size (int): The size of the kernel (should be odd).
    sigma (float): The standard deviation of the Gussian distribution.

  Returns:
    np.ndarray: The Gaussian kernel.
  """

  # Ensure the kernel size is odd
  if size % 2 == 0:
    size += 1

  #Create coordinate grid
  ax = np.linspace(-(size // 2), size // 2, size)
  xx, yy = np.meshgrid(ax, ax)

  #Compute the Gaussian kernel
  kernel = np.exp(-0.5 * (xx**2 + yy**2) / sigma**2)

  #Normalize the kernel
  kernel /= (2 * np.pi * sigma**2)
  kernel = kernel / np.sum(kernel) #Normalize to make the sum of all elements equal to 1

  return kernel


In [10]:
def apply_filte_and_transform(image, sigma, angle):
  """Apply Gaussian blur and rottaion tto an image."""
  #Convert image to grayscale if its RGB
  if len(image.shape) == 3:
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

  #Create Gaussian kernel - Thumb rule to select Gaussian kernel size
  kernel_size = int(6 * sigma + 1)
  kernel = gaussian_kernel(kernel_size, sigma)

  #Apply Gaussian blur
  depth = -1 #(-1 for all depth available)
  blurred_image = cv2.filter2D(image, depth, kernel)

  #Rotate the image
  center = (blurred_image.shape[1] / 2, blurred_image.shape[0] / 2)
  rotation_matrix = cv2.getRotationMatrix2D(center, angle, 1.0)
  rotated_image = cv2.warpAffine(blurred_image, rotation_matrix, (blurred_image.shape[1], blurred_image.shape[0]))

  return blurred_image, rotated_image

In [ ]:
import matplotlib.pyplot as plt
import cv2

#Load the image
image = cv2.imread('image.jpg', cv2.IMREAD_GRAYSCALE)

#Apply Gaussian blur and rotation
sigma = 1.0 # Standard deviation for Gaussian kernel
angle = 45.0 #Angle for rotation
blurred_image, rotated_image = apply_filte_and_transform(image, sigma, angle)


#Display the image
plt.figure(figsize=(12, 6))

#Original image
plt.subplot(1, 3, 1)
plt.title('Original Image')
plt.imshow(image, cmap='gray')
plt.axis('off')


#Gaussian Blurred Image
plt.subplot(1, 3, 2)
plt.title('Gaussian Blurred Image')
plt.imshow(blurred_image, cmap='gray')
plt.axis('off')

#Rotate Image after Gaussian Blue
plt.subplot(1, 3, 3)
plt.title('Rotated Image')
plt.imshow(rotated_image, cmap='gray')
plt.axis('off')

plt.show()
